[k3s_server]
control_plane ansible_host=3.148.211.26

[k3s_agents]
worker_1 ansible_host=18.117.253.171
worker_2 ansible_host=3.15.170.109

[k3s:children]
k3s_server
k3s_agents

[k3s:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
